Cleaned up the script files

diff --git a/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_disp b/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_disp
--- a/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_disp
+++ b/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_disp
@@ -3,7 +3,7 @@
 # Special char: ^ to add a new line
 # Set seconds to 0 to display indefinitely (until the next notif)
 
-NOTIFICATION_DISPLAY="/sys/class/graphics/fb0/notification"
+NOTIFICATION_DISPLAY=/sys/class/graphics/fb0/notification
 
 display_usage() { 
     echo -e "Usage:\n$(basename ${0}) nb_seconds_display message_to_display\n" 
@@ -18,21 +18,21 @@ fi
 
 # Get number of seconds to display notif
 nb_secs=${1}
-if ! [ "${nb_secs}" -ne "${nb_secs}" ] 2> /dev/null; then
-    echo "error: \"${nb_secs}\" is not a number" >&2
+if ! [ ! "${nb_secs}" -ne "${nb_secs}" ] 2> /dev/null; then
+    echo "error: ${nb_secs} is not a number" >&2
     exit 1
 fi
 
 # Print notif
-printf "${*:2}" > "${NOTIFICATION_DISPLAY}"
+printf "${*:2}" > ${NOTIFICATION_DISPLAY}
 
 # Clear notif if NB_SECS is not 0, otherwise never clear
-if [ "${nb_secs}" -ne "0" ]; then
+if [ ${nb_secs} -ne 0 ]; then
 
     # Wait time before clearing notif
     sleep ${nb_secs}
 
     # Clear notif
-    printf "clear" > "${NOTIFICATION_DISPLAY}"
+    printf "clear" > ${NOTIFICATION_DISPLAY}
 fi
 exit 0
diff --git a/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_set b/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_set
--- a/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_set
+++ b/FunKey/board/funkey/rootfs-overlay/usr/local/sbin/notif_set
@@ -3,14 +3,14 @@
 # Special char: ^ to add a new line
 # Set seconds to 0 to display indefinitely (until the next notif_set)
 
-NOTIFICATION_DISPLAY="/sys/class/graphics/fb0/notification"
+NOTIFICATION_DISPLAY=/sys/class/graphics/fb0/notification
 
 display_usage() { 
     echo -e "Usage:\n$(basename ${0}) nb_seconds_display message_to_display\n" 
 } 
  
 # If less than two arguments supplied, display usage 
-if [  $# -le 1 ]; then 
+if [  ${#} -le 1 ]; then 
     echo "Erase previous notif and display new one in background process for a certain amount of time"
     echo "Special char: ^ to add a new line"
     echo "Set seconds to 0 to display indefinitely (until the next $(basename ${0}))"
@@ -20,8 +20,8 @@ fi
 
 # Get number of seconds to display notif
 nb_secs=${1}
-if ! [ "${nb_secs}" -ne "${nb_secs}" ]; then
-     echo "error: \"${nb_secs}\" is not a number" >&2
+if ! [ ! "${nb_secs}" -ne "${nb_secs}" ]; then
+     echo "error: ${nb_secs} is not a number" >&2
      exit 1
 fi
 
@@ -29,7 +29,7 @@ fi
 pkill notif_disp 2> /dev/null
 
 ## Clear previous notif
-#printf "clear" > "${NOTIFICATION_DISPLAY}"
+#printf "clear" > ${NOTIFICATION_DISPLAY}
 
 # Print new notif
 notif_disp "$@" &
