test scripts

diff --git a/PCBA/board/funkey/rootfs-overlay/bin/test-gpio b/PCBA/board/funkey/rootfs-overlay/bin/test-gpio
--- a/PCBA/board/funkey/rootfs-overlay/bin/test-gpio
+++ b/PCBA/board/funkey/rootfs-overlay/bin/test-gpio
@@ -1,18 +1,22 @@
 #!/bin/sh
 
 if [ $# -ne 2 ]; then
-    echo "ERROR Wrong number of arguments $#"
+    echo "ERROR GPIO ARGS"
     exit 1
 fi
 pin=$(gpiofind "${1}")
 if [ $? -ne 0 ]; then
-    echo "ERROR Unknown GPIO ${1}"
+    echo "ERROR GPIO PIN"
     exit 1
 fi
 case ${2} in
     0) value=${2};;
     1) value=${2};;
-    *) echo "ERROR Bad value ${2}"; exit 1;;
+    *) echo "ERROR GPIO VALUE"; exit 1;;
 esac
 gpioset ${pin}=${value}
-echo "OK"
+if [ $? -ne 0 ]; then
+    echo "ERROR GPIO I2C"
+else
+    echo "OK"
+fi
diff --git a/PCBA/board/funkey/rootfs-overlay/bin/test-speaker b/PCBA/board/funkey/rootfs-overlay/bin/test-speaker
--- a/PCBA/board/funkey/rootfs-overlay/bin/test-speaker
+++ b/PCBA/board/funkey/rootfs-overlay/bin/test-speaker
@@ -2,11 +2,23 @@
 
 # Turn on Power Amplifier
 gpioset $(gpiofind "PA")=1
+if [ $? -ne 0 ]; then
+    echo "ERROR SPEAKER ON"
+else
 
-# Play 1kHz sine wave
-speaker-test -t sine -s 1 -f 1000 >/dev/null 2>&1
+    # Play 1kHz sine wave
+    speaker-test -t sine -s 1 -f 1000 >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+	echo "ERROR SPEAKER SINE"
+	gpioset $(gpiofind "PA")=0
+    else
 
-# Turn off Power Amplifier
-gpioset $(gpiofind "PA")=0
-
-echo "OK"
+	# Turn off Power Amplifier
+	gpioset $(gpiofind "PA")=0
+	if [ $? -ne 0 ]; then
+	    echo "ERROR SPEAKER OFF"
+	else
+	    echo "OK"
+	fi
+    fi
+fi
